DROP SCHEMA IF EXISTS patients_ucm CASCADE;
CREATE SCHEMA patients_ucm;

DROP SCHEMA IF EXISTS events_ucm CASCADE;
CREATE SCHEMA events_ucm;

DROP SCHEMA IF EXISTS lookup_ucm CASCADE;
CREATE SCHEMA lookup_ucm;
